### PR TITLE
Templates beta8

### PR DESCRIPTION
**Pull request by natashasandiego**
Illustrator template is updated to mach Sketch template

### CODE REVIEW

**Comment by kyleledbetter** [comment]
@natashasandiego did you make changes to the Sketch file intentionally in this pull request or did you accidentally start this branch from a branch other than develop?

**Comment by natashasandiego** [comment]
@kyleledbetter please ignore the Sketch file changes - I didn't do it intentionally. Only Illustrator file is updated

**Comment by kyleledbetter** [comment]
I can't ignore though (Github can't ignore), the sketch file is included in this PR. You'll need to create a new branch off of develop and just include the Illustrator file in it, and close this PR

**Comment by kyleledbetter** [comment]
I went ahead and added your Illustrator updates in a new branch and merged it https://github.com/Teradata/covalent-resources/pull/5 closing this one now

**Pull request closed without merging**
