### PR TITLE
feat(): design pattern mini side nav

### PR DESCRIPTION
**Pull request by joejcarey**
## Description
moved the design pattern patterns mini side nav into it's own branch for review 

### What's included?
- Mini side nav pattern and routes  

#### Test Steps
- [x] Close mini side nav - Select left arrow at bottom of mini side nav to close menu. 
- [x] Open mini side nav - Select right arrow at bottom of mini side nav to open menu.

#### Closed mini side nav
Screen Shot 2019-03-25 at 9 00 28 AM

#### Opened mini side nav
Screen Shot 2019-03-25 at 9 00 17 AM

### CODE REVIEW

**Review by jennmedellin — APPROVED** [review]
UX LGTM

**Comment by stevenov7** [comment]
There is an awkward jump when minimizing and expanding. It look like it should be a more smoother transition.

rec-0

**Review by ghost — CHANGES_REQUESTED** [review]
There is an awkward jump when minimizing and expanding. It look like it should be a more smoother transition.

rec-0

**Comment by jennmedellin** [comment]
Closing this, I'll submit another PR once we're ready to create patterns for the design system

**Pull request closed without merging**
